name: Build and Release SECI app

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Get dependencies
        run: flutter pub get
      - name: Build Windows release
        run: flutter build windows --release

      # Step to create the MSIX installer
      - name: Create MSIX installer
        # run: flutter pub run msix:create
        run: flutter pub run msix:create --auto-accept

      # Step to create the GitHub Release
      - name: Create github Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/windows/x64/runner/Release/*
            *.msix # This will find the .msix file in the root directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
